import { matchPath } from 'react-router-dom';

export const ROUTE_PATTERNS = Object.freeze([
  '/',
  '/home',
  '/about',
  '/contact',
  '/privacy',
  '/terms',
  '/feed',
  '/pulse',
  '/login',
  '/register',
  '/auth/google/complete',
  '/forgot-password',
  '/reset-password',
  '/verify-email',
  '/pricing',
  '/billing/success',
  '/billing/cancel',
  '/league/:leagueSlug',
  '/league/:leagueSlug/standings',
  '/league/:leagueSlug/games',
  '/league/:leagueSlug/teams/:teamSlug/players/:leaguePlayerId',
  '/league/:leagueSlug/teams/:teamSlug',
  '/teams',
  '/teams/new',
  '/teams/:teamId/edit',
  '/opponents/:opponentSlug',
  '/teams/:teamId/players/:playerId',
  '/players/:userId',
  '/teams/:teamId',
  '/leagues',
  '/leagues/new',
  '/leagues/:leagueId/manage',
  '/leagues/:leagueId/teams/:leagueTeamId',
  '/leagues/:leagueId/games/new',
  '/leagues/:leagueId',
  '/admin/leagues/new',
  '/admin/leagues/:leagueId',
  '/admin/leagues/:leagueId/teams/:leagueTeamId',
  '/admin/leagues/:leagueId/games/new',
  '/admin/leagues/:leagueId/schedule',
  '/admin/leagues/:leagueId/teams/new',
  '/admin/teams/:teamId',
  '/games/new',
  '/games',
  '/games/:gameId',
  '/my-sporty',
  '/onboarding',
  '/following',
  '/admin',
  '/admin/social/instagram',
  '/dashboard',
  '/games/:gameId/track',
]);

export function getRoutePattern(pathname) {
  return (
    ROUTE_PATTERNS.find((pattern) => matchPath({ path: pattern, end: true }, pathname)) || 'unknown'
  );
}
